---
# TP LABO - Fenómeno de El Niño
---

Poner algo que diga de qué va el colab, despues se completa, son detalles

# 🔍 3.1 Exploración inicial de los Datasets

### Dataset "smn_estaciones_meteorologicas21-26.xlsx":

In [7]:
#Importamos las librerías que vamos a utilizar
import pandas as pd #para manejo de archivos de datos

In [8]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "smn_estaciones_meteorologicas21-26.xlsx")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/smn_estaciones_meteorologicas21-26.xlsx

In [9]:
#Cargamos los datos
estaciones = pd.read_excel(URL + "smn_estaciones_meteorologicas21-26.xlsx")   # read_excel: leer una planilla de Excel

In [10]:
# Leemos las primeras 5 lineas del principio:
estaciones.head()

   NRO_OMM             NOMBRE     PROVINCIA   LATITUD  LONGITUD  ALTURA
0    87544       PEHUAJO AERO  BUENOS AIRES -35.84070 -61.85978      87
1    87548         JUNIN AERO  BUENOS AIRES -34.55251 -60.93127      81
2    87550     NUEVE DE JULIO  BUENOS AIRES -35.43899 -60.88191      76
3    87553  SAN FERNANDO AERO  BUENOS AIRES -34.45502 -58.58449       5
4    87563         LAS FLORES  BUENOS AIRES -36.04149 -59.13724      36

In [11]:
# Leemos las últimas 5 lineas del dataset:
estaciones.tail()

,NRO_OMM,NOMBRE,PROVINCIA,LATITUD,LONGITUD,ALTURA
87,87470,EL TRÉBOL,SANTA FE,-32.19216,-61.71198,96
88,87129,SANTIAGO DEL ESTERO AERO,SANTIAGO DEL ESTERO,-27.75481,-64.29980,199
89,87934,RÍO GRANDE B.A.,TIERRA DEL FUEGO,-53.78026,-67.75871,22
90,87938,USHUAIA AERO,TIERRA DEL FUEGO,-54.84005,-68.30342,57
91,87121,TUCUMÁN AERO,TUCUMÁN,-26.83730,-65.10843,450

In [12]:
#Describimos la estructura del Dataset:
#--------------------------------------

#Tipo de datos definidos:
print('Tipo de datos:')
print(estaciones.dtypes)
print('')
print('-'*50)

#Veamos sus dimensiones:
print("Dimensiones:", estaciones.shape, "  ← (Filas, Columnas)")
print('-'*50)
print('')

#Veamos la calidad de datos: hay varios puntos
print('Tiene nulos? No! No tiene Nulos!')
print(estaciones.info())
print('')
print('Pero por las dudas verifico los nulos por columna:')
print(estaciones.isnull().sum())
print('')
print('Confirmado, no hay valores nulos ya que dieron todas cero.')
print('-'*50)
print('')

print('Revisamos si hay duplicados:')
print("Filas duplicadas:", estaciones.duplicated().sum())
if estaciones.duplicated().sum() == 0:
  print('No hay duplicados!')
else:
  print('Hay filas duplicadas, vamos a revisar un poco más y eliminarlas')
print('-'*50)
print('')

print('Obtenemos los datos estadísticos básicos: en este dataset no nos será de mucha utilidad')
display(estaciones.describe().T)

Tipo de datos:
NRO_OMM        int64
NOMBRE        object
PROVINCIA     object
LATITUD      float64
LONGITUD     float64
ALTURA         int64
dtype: object

--------------------------------------------------
Dimensiones: (92, 6)   ← (Filas, Columnas)
--------------------------------------------------

Tiene nulos? No! No tiene Nulos!
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NRO_OMM    92 non-null     int64
 1   NOMBRE     92 non-null     object
 2   PROVINCIA  92 non-null     object
 3   LATITUD    92 non-null     float64
 4   LONGITUD   92 non-null     float64
 5   ALTURA     92 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 4.4+ KB
None

Pero por las dudas verifico los nulos por columna:
NRO_OMM      0
NOMBRE       0
PROVINCIA    0
LATITUD      0
LONGITUD     0
ALTURA       0
dtype: int64

Confirmado, no hay valores nulos ya que dieron todas cero.
--------------------------------------------------

Revisamos si hay duplicados:
Filas duplicadas: 0
No hay duplicados!
--------------------------------------------------

Obtenemos los datos estadísticos básicos: en este dataset no nos será de mucha utilidad

,count,mean,std,min,25%,50%,75%,max
NRO_OMM,92.0,87475.369565,256.950404,87007.00000,87266.750000,87488.50000,87645.750000,87938.00000
LATITUD,92.0,-34.387620,7.009355,-54.84005,-37.294213,-33.70020,-29.828997,-22.10343
LONGITUD,92.0,-63.227429,4.398605,-72.05149,-66.461883,-63.54759,-59.578342,-53.67121
ALTURA,92.0,341.423913,476.374177,5.00000,53.750000,146.00000,451.000000,3459.00000

---