---
# TP LABO - Fenómeno de El Niño
---

Poner algo que diga de qué va el colab, despues se completa, son detalles

# 🔍 3.1 Exploración inicial de los Datasets

### Dataset "smn_estaciones_meteorologicas21-26.xlsx":

In [44]:
#Importamos las librerías que vamos a utilizar
import pandas as pd #para manejo de archivos de datos
import numpy as np #para realizar cálculos numéricos y matemáticos
import matplotlib.pyplot as plt #para graficar

In [45]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "smn_estaciones_meteorologicas21-26.xlsx")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/smn_estaciones_meteorologicas21-26.xlsx

In [46]:
#Cargamos los datos
estaciones = pd.read_excel(URL + "smn_estaciones_meteorologicas21-26.xlsx")   # read_excel: leer una planilla de Excel

In [47]:
# Leemos las primeras 5 lineas del principio:
estaciones.head()

   NRO_OMM             NOMBRE     PROVINCIA   LATITUD  LONGITUD  ALTURA
0    87544       PEHUAJO AERO  BUENOS AIRES -35.84070 -61.85978      87
1    87548         JUNIN AERO  BUENOS AIRES -34.55251 -60.93127      81
2    87550     NUEVE DE JULIO  BUENOS AIRES -35.43899 -60.88191      76
3    87553  SAN FERNANDO AERO  BUENOS AIRES -34.45502 -58.58449       5
4    87563         LAS FLORES  BUENOS AIRES -36.04149 -59.13724      36

In [48]:
# Leemos las últimas 5 lineas del dataset:
estaciones.tail()

,NRO_OMM,NOMBRE,PROVINCIA,LATITUD,LONGITUD,ALTURA
87,87470,EL TRÉBOL,SANTA FE,-32.19216,-61.71198,96
88,87129,SANTIAGO DEL ESTERO AERO,SANTIAGO DEL ESTERO,-27.75481,-64.29980,199
89,87934,RÍO GRANDE B.A.,TIERRA DEL FUEGO,-53.78026,-67.75871,22
90,87938,USHUAIA AERO,TIERRA DEL FUEGO,-54.84005,-68.30342,57
91,87121,TUCUMÁN AERO,TUCUMÁN,-26.83730,-65.10843,450

In [49]:
#Describimos la estructura del Dataset:
#--------------------------------------

#Tipo de datos definidos:
print('Tipo de datos:')
print(estaciones.dtypes)
print('')
print('-'*50)

#Veamos sus dimensiones:
print("Dimensiones:", estaciones.shape, "  ← (Filas, Columnas)")
print('-'*50)
print('')

#Veamos la calidad de datos: hay varios puntos
print('Tiene nulos? No! No tiene Nulos!')
print(estaciones.info())
print('')
print('Pero por las dudas verifico los nulos por columna:')
print(estaciones.isnull().sum())
print('')
print('Confirmado, no hay valores nulos ya que dieron todas cero.')
print('-'*50)
print('')

print('Revisamos si hay duplicados:')
print("Filas duplicadas:", estaciones.duplicated().sum())
if estaciones.duplicated().sum() == 0:
  print('No hay duplicados!')
else:
  print('Hay filas duplicadas, vamos a revisar un poco más y eliminarlas')
print('-'*50)
print('')

print('Obtenemos los datos estadísticos básicos: en este dataset no nos será de mucha utilidad')
display(estaciones.describe().T)

Tipo de datos:
NRO_OMM        int64
NOMBRE        object
PROVINCIA     object
LATITUD      float64
LONGITUD     float64
ALTURA         int64
dtype: object

--------------------------------------------------
Dimensiones: (92, 6)   ← (Filas, Columnas)
--------------------------------------------------

Tiene nulos? No! No tiene Nulos!
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NRO_OMM    92 non-null     int64
 1   NOMBRE     92 non-null     object
 2   PROVINCIA  92 non-null     object
 3   LATITUD    92 non-null     float64
 4   LONGITUD   92 non-null     float64
 5   ALTURA     92 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 4.4+ KB
None

Pero por las dudas verifico los nulos por columna:
NRO_OMM      0
NOMBRE       0
PROVINCIA    0
LATITUD      0
LONGITUD     0
ALTURA       0
dtype: int64

Confirmado, no hay valores nulos ya que dieron todas cero.
--------------------------------------------------

Revisamos si hay duplicados:
Filas duplicadas: 0
No hay duplicados!
--------------------------------------------------

Obtenemos los datos estadísticos básicos: en este dataset no nos será de mucha utilidad

,count,mean,std,min,25%,50%,75%,max
NRO_OMM,92.0,87475.369565,256.950404,87007.00000,87266.750000,87488.50000,87645.750000,87938.00000
LATITUD,92.0,-34.387620,7.009355,-54.84005,-37.294213,-33.70020,-29.828997,-22.10343
LONGITUD,92.0,-63.227429,4.398605,-72.05149,-66.461883,-63.54759,-59.578342,-53.67121
ALTURA,92.0,341.423913,476.374177,5.00000,53.750000,146.00000,451.000000,3459.00000

## Dataset "smn_datos_meteorologicos_1991_2020.xlxs":

In [50]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "smn_datos_meteorologicos_1991_2020.xlsx")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/smn_datos_meteorologicos_1991_2020.xlsx

In [51]:
#Cargamos los datos del dataset período 1991-2020
smn_1991_2020 = pd.read_excel(URL + "smn_datos_meteorologicos_1991_2020.xlsx")   # read_excel: leemos el archivo excel

A continuación comenzamos a trabajar con el Datase propiamente dicho. Vamos a describir su estructura.

A) Buscamos ver cuántos registros contiene el archivo y cuántas variables se encuentran disponibles. Nos va permitir tener una idea del tamaño del conjunto de datos con el que vamos a trabajar.

B) Revisamos el nombre de las columnas lo que nos permite saber qué variables meteorológicas contiene. También ver otras posibles columnas como ser nombre de la estación, fecha de medición, etc.

C) Examinamos los tipos de datos. Vemos cómo Python está intepretando la información del set de datos. Por ejemplo, ¿las fechas están como texto? ¿valores numéricos están como tales?

D) Analizamos si hay valores faltantes en el Dataset.

E) Verificamos si existen registros que contienen exactamente la misma información en todas sus columnas (duplicaciones).

F) Un poco de Estadística Descriptiva de los datos.

In [52]:
# Leemos las primeras 5 filas para comenzar a tener una idea de este set de datos:
smn_1991_2020.head()

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL
0,87007,LA QUIACA OBSERVATORIO,1991-01-01,18.4,5.4,13.3,5.2,S/D,5,9,6,671.4,64,7
1,87007,LA QUIACA OBSERVATORIO,1991-01-02,18.2,8.4,12.3,8,S/D,32,15,8,670.7,73,7
2,87007,LA QUIACA OBSERVATORIO,1991-01-03,19.4,6,13.7,NaN,S/D,5,9,4,672,61,4
3,87007,LA QUIACA OBSERVATORIO,1991-01-04,19.3,4.9,13.1,NaN,S/D,7,15,2,673.2,55,4
4,87007,LA QUIACA OBSERVATORIO,1991-01-05,21,6,14.2,NaN,S/D,5,15,6,673.4,60,4

In [53]:
# Leemos las últimas 5 filas del dataset:
smn_1991_2020.tail()

,NRO_OMM,NOMBRE,FECHA,TMAX,TMIN,TMEDIA,PRECIP,HELIOF,VTO_MDIR,VTO_MVEL,VEL_MED,PRE_EST,HUM_REL,NUB_TOTAL
992179,87938,USHUAIA AERO,2020-12-27,22.2,7.2,13.6,0.0,8.7,29,93,16,992.7,58,5
992180,87938,USHUAIA AERO,2020-12-28,17.5,7.3,9.7,2.0,4.6,23,44,16,1002.4,75,7
992181,87938,USHUAIA AERO,2020-12-29,13.5,6.0,9.5,0.0,10.6,23,57,18,995.6,71,7
992182,87938,USHUAIA AERO,2020-12-30,12.8,5.4,8.8,NaN,0.9,23,54,15,991.7,66,6
992183,87938,USHUAIA AERO,2020-12-31,15.5,9.6,11.8,0.0,10.0,23,57,28,988.7,66,5

In [54]:
#Describimos la estructura del Dataset:
#------------------------------------------------------

#1 - Dimensiones del Conjunto de Datos

# Consultamos las dimensiones del conjunto de datos.
# shape devuelve la cantidad de filas y columnas.

print(f"Dimensiones: {smn_1991_2020.shape}")

# Mostramos por separado la cantidad de registros y variables.
print(f"\nCantidad de filas: {smn_1991_2020.shape[0]}")
print(f"\nCantidad de columnas: {smn_1991_2020.shape[1]}")
print('')


#2 - Tipos de datos

# Consultamos el tipo de dato de cada columna.
# Esto permite distinguir variables numéricas, textos y fechas.

print(smn_1991_2020.dtypes)
print('')


# Obtenemos información general de la tabla: tipo de dato y cantidad de valores no nulos de cada columna.

print(smn_1991_2020.info())
print('')

#Examinando la calidad de los datos del Dataset:
#------------------------------------------------------

#3 - Valores faltantes

# Contamos los valores faltantes en cada columna.

print(smn_1991_2020.isnull().sum())
print('')

#4 - Valores duplicados

# Contamos cuántas filas están completamente duplicadas.

print(f"\nFilas duplicadas: {smn_1991_2020.duplicated().sum()}")
print('')


#Un poco de Estadística Descriptiva de los datos del Dataset:
#------------------------------------------------------

#print('Veamos información estadísticas descrptiva básica:')
#display(smn_1991_2020.describe().T)

Dimensiones: (992184, 14)

Cantidad de filas: 992184

Cantidad de columnas: 14

NRO_OMM               int64
NOMBRE               object
FECHA        datetime64[ns]
TMAX                 object
TMIN                 object
TMEDIA               object
PRECIP               object
HELIOF               object
VTO_MDIR             object
VTO_MVEL             object
VEL_MED              object
PRE_EST              object
HUM_REL              object
NUB_TOTAL            object
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992184 entries, 0 to 992183
Data columns (total 14 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   NRO_OMM    992184 non-null  int64
 1   NOMBRE     992184 non-null  object
 2   FECHA      992184 non-null  datetime64[ns]
 3   TMAX       992184 non-null  object
 4   TMIN       992184 non-null  object
 5   TMEDIA     992184 non-null  object
 6   PRECIP     274605 non-null  object
 7   HELIOF     992184 non-null  object
 8   VTO_MDIR   992184 non-null  object
 9   VTO_MVEL   992184 non-null  object
 10  VEL_MED    992184 non-null  object
 11  PRE_EST    992184 non-null  object
 12  HUM_REL    992184 non-null  object
 13  NUB_TOTAL  992184 non-null  object
dtypes: datetime64[ns](1), int64(1), object(12)
memory usage: 106.0+ MB
None

NRO_OMM           0
NOMBRE            0
FECHA             0
TMAX              0
TMIN              0
TMEDIA            0
PRECIP       717579
HELIOF            0
VTO_MDIR          0
VTO_MVEL          0
VEL_MED           0
PRE_EST           0
HUM_REL           0
NUB_TOTAL         0
dtype: int64


Filas duplicadas: 0

Algunas cuestiones que detectamos en este primer análisis:

TMAX                 object
TMIN                 object
TMEDIA               object
PRECIP               object
HELIOF               object
VTO_MDIR             object
VTO_MVEL             object
VEL_MED              object
PRE_EST              object
HUM_REL              object
NUB_TOTAL            object

11 variables meteorológicas aparecen como object. Varias de ellas deberían ser numéricas como por Precitipación, TMAX, TMIN.

Precipitación presenta 717579 valores nulos de un total de 992184. El 72,32%

Se trabajo con IA para analizar cuántos valores de cada variable meteorológica no pueden convertirse directamente en números. Esto nos permitirá decidir cómo preparar las columnas para calcular estadísticas descriptivas.

PROMPT: Hemos obtenido los siguentes resultados al analizar el tipo de datos. Variables que deberían ser numéricas aparecen como texto. Antes de comenzar a trabajar con los ajustes que pudieran ser necesarios, ¿podemos pensar un código para ver si los datos igualmente podrían ser trabajados con Pandas?

In [55]:
# Seleccionamos las columnas que contienen variables meteorológicas.
# Excluimos los identificadores de estación y la fecha.

variables_meteo = smn_1991_2020.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Revisamos los valores que no pueden interpretarse como números.
# errors="coerce" convierte temporalmente esos valores en NaN.
# No modificamos los datos originales.

for columna in variables_meteo:
    valores = pd.to_numeric(smn_1991_2020[columna], errors="coerce")

    # Contamos los valores no nulos originales que no son numéricos.
    no_numericos = (
        valores.isna() & smn_1991_2020[columna].notna()
    ).sum()

    print(columna, ":", no_numericos, "valores no numéricos")

TMAX : 20993 valores no numéricos
TMIN : 24425 valores no numéricos
TMEDIA : 8551 valores no numéricos
PRECIP : 2244 valores no numéricos
HELIOF : 126035 valores no numéricos
VTO_MDIR : 14836 valores no numéricos
VTO_MVEL : 14831 valores no numéricos
VEL_MED : 10455 valores no numéricos
PRE_EST : 26755 valores no numéricos
HUM_REL : 9845 valores no numéricos
NUB_TOTAL : 9264 valores no numéricos

Confirmamos que todas las variables meteorológicas tienen algunos valores que pandas no puede interpretar directamente como números.

A partir de estos resultados, y teniendo en cuenta que una columna aparezca como object no significa que todos sus valores sean no numéricos (algo de esto ya lo podemos intuir de ver los valores no númericos y el resultado del análisis del tipo de datos), analizamos valores numéricos, no numéricos y nulos para estas variables meteorológicas.

Se trabaja con IA para la formulación del código que nos permita ver esto último. PROMPT: Vamos a armar un código para contar los valores numéricos, no numéricos y nulos de todas las variables meteorológicas del DataFrame smn_1991_2020, teniendo en cuenta no modificar los datos originales.

In [56]:
# Seleccionamos las columnas meteorológicas.

variables_meteo = smn_1991_2020.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Recorremos las variables para conocer cuántos registros son convertibles a números, no convertibles o nulos.

for columna in variables_meteo:

    convertida = pd.to_numeric(
        smn_1991_2020[columna],
        errors="coerce"
    )

    numericos = convertida.notna().sum()

    no_numericos = (
        convertida.isna() & smn_1991_2020[columna].notna()
    ).sum()

    nulos = smn_1991_2020[columna].isna().sum()

    print(
        columna,
        "| Numéricos:", numericos,
        "| No numéricos:", no_numericos,
        "| Nulos:", nulos
    )

TMAX | Numéricos: 971191 | No numéricos: 20993 | Nulos: 0
TMIN | Numéricos: 967759 | No numéricos: 24425 | Nulos: 0
TMEDIA | Numéricos: 983633 | No numéricos: 8551 | Nulos: 0
PRECIP | Numéricos: 272361 | No numéricos: 2244 | Nulos: 717579
HELIOF | Numéricos: 866149 | No numéricos: 126035 | Nulos: 0
VTO_MDIR | Numéricos: 977348 | No numéricos: 14836 | Nulos: 0
VTO_MVEL | Numéricos: 977353 | No numéricos: 14831 | Nulos: 0
VEL_MED | Numéricos: 981729 | No numéricos: 10455 | Nulos: 0
PRE_EST | Numéricos: 965429 | No numéricos: 26755 | Nulos: 0
HUM_REL | Numéricos: 982339 | No numéricos: 9845 | Nulos: 0
NUB_TOTAL | Numéricos: 982920 | No numéricos: 9264 | Nulos: 0

A partir de los resultados, vamos a evaluar qué valores no numéricos aparecen en nuestro set de datos. Por ejemplo: S/D, un guión, un espacio.

PROMPT: Escribir un código que nos permita identificar exactamente qué valores no numéricos aparecen en cada variable meteorológica y cuántas veces se repiten.

In [57]:
# Seleccionamos las variables meteorológicas.
# Excluimos el código de estación, el nombre y la fecha.

variables_meteo = smn_1991_2020.columns.drop(
    ["NRO_OMM", "NOMBRE", "FECHA"]
)

# Recorremos cada variable meteorológica.

for columna in variables_meteo:

    # Intentamos convertir los valores a números.
    # Los que no pueden convertirse pasan temporalmente a NaN.

    convertida = pd.to_numeric(
        smn_1991_2020[columna],
        errors="coerce"
    )

    # Seleccionamos los valores que no pudieron convertirse,
    # excluyendo aquellos que ya eran nulos.

    no_numericos = smn_1991_2020.loc[
        convertida.isna() & smn_1991_2020[columna].notna(),
        columna
    ]

    # Mostramos los distintos valores no numéricos
    # y la cantidad de veces que aparece cada uno.

    print("\nVariable:", columna)
    print(no_numericos.value_counts(dropna=False))

Variable: TMAX
TMAX
S/D    20993
Name: count, dtype: int64

Variable: TMIN
TMIN
S/D    24425
Name: count, dtype: int64

Variable: TMEDIA
TMEDIA
S/D    8551
Name: count, dtype: int64

Variable: PRECIP
PRECIP
S/D    2244
Name: count, dtype: int64

Variable: HELIOF
HELIOF
S/D    126035
Name: count, dtype: int64

Variable: VTO_MDIR
VTO_MDIR
S/D    14836
Name: count, dtype: int64

Variable: VTO_MVEL
VTO_MVEL
S/D    14831
Name: count, dtype: int64

Variable: VEL_MED
VEL_MED
S/D    10455
Name: count, dtype: int64

Variable: PRE_EST
PRE_EST
S/D    26755
Name: count, dtype: int64

Variable: HUM_REL
HUM_REL
S/D    9845
Name: count, dtype: int64

Variable: NUB_TOTAL
NUB_TOTAL
S/D    9264
Name: count, dtype: int64

Este último resultado nos permitió confirmar que en las 11 variables meteorológicas el único valor no numérico identificado es S/D

# Dataset "indices_enso_noaa_pacifico.csv":

In [58]:
# Buscamos el archivo en el GitHub
# Apunta a la carpeta DF/ del repositorio en GitHub. Será el mismo URL para todos los Dataframes.
URL = "https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/"

print(URL + "indices_enso_noaa_pacifico.csv")   # así se arma la dirección de cada archivo

https://github.com/enrique20delgado-create/TP-Labo-ElNino-2C2026/raw/refs/heads/main/DF/indices_enso_noaa_pacifico.csv

In [60]:
prueba = pd.read_csv(URL + "indices_enso_noaa_pacifico.csv")
prueba.head() # Muestro las 5 primeras filas

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
0,1950-01-01,1950,JAN,23.01,-1.55,23.56,-2.10,24.55,-1.99,26.94,...,-2.34,DJ,NaN,DJF,-1.32,-1.19,La Niña,Moderado,La Niña,Moderado
1,1950-02-01,1950,FEB,24.32,-1.78,24.89,-1.52,25.06,-1.69,26.67,...,-1.04,JF,NaN,JFM,-1.20,-1.08,La Niña,Moderado,La Niña,Moderado
2,1950-03-01,1950,MAR,25.11,-1.38,26.36,-0.84,25.87,-1.42,26.52,...,0.24,FM,NaN,FMA,-1.12,-0.96,La Niña,Moderado,La Niña,Moderado
3,1950-04-01,1950,APR,23.63,-1.90,26.44,-1.14,26.28,-1.54,26.90,...,0.01,MA,NaN,MAM,-1.08,-1.00,La Niña,Moderado,La Niña,Moderado
4,1950-05-01,1950,MAY,22.68,-1.74,25.69,-1.57,26.18,-1.75,27.73,...,-0.55,AM,NaN,AMJ,-1.10,-0.99,La Niña,Moderado,La Niña,Moderado

In [61]:
prueba.tail() # Muestro las 5 ultimas filas

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
916,2026-05-01,2026,MAY,26.23,1.82,28.41,1.16,28.83,0.90,30.00,...,-1.2693,AM,0.27,AMJ,0.95,0.49,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
917,2026-06-01,2026,JUN,25.94,2.82,28.33,1.71,29.17,1.44,30.19,...,-0.5005,MJ,1.52,MJJ,1.39,0.97,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
918,2026-07-01,2026,JUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6149,JJ,2.41,JJA,1.80,1.36,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
919,2026-08-01,2026,AUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0797,JA,2.54,JAS,2.16,1.69,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
920,2026-09-01,2026,SEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.6415,AS,2.37,ASO,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
print("Dimensiones", prueba.shape)
print("Filas:", prueba.shape[0], " Columnas:", prueba.shape[1])

Dimensiones (921, 26)
Filas: 921  Columnas: 26

In [63]:
prueba.info() # Me sirve para saber que tipo de objeto tiene cada columna, tambien veo los null como por ejemplo de la columna 18 "MEI.v2" tiene 573 no null(datos) y el resto estan vacios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  921 non-null    object
 1   Year                  921 non-null    int64
 2   Month                 921 non-null    object
 3   Nino 1+2 SST          918 non-null    float64
 4   Nino 1+2 SST Anomaly  918 non-null    float64
 5   Nino 3 SST            918 non-null    float64
 6   Nino 3 SST Anomaly    918 non-null    float64
 7   Nino 3.4 SST          918 non-null    float64
 8   Nino 3.4 SST Anomaly  918 non-null    float64
 9   Nino 4 SST            918 non-null    float64
 10  Nino 4 SST Anomaly    918 non-null    float64
 11  TNI                   917 non-null    float64
 12  SOI                   909 non-null    float64
 13  SOI estandarizado     909 non-null    float64
 14  OLR                   612 non-null    float64
 15  OLR anomalia          612 non-null    float64
 16  PNA                   921 non-null    float64
 17  Season (2-Month)      921 non-null    object
 18  MEI.v2                573 non-null    float64
 19  Season (3-Month)      921 non-null    object
 20  ONI                   920 non-null    float64
 21  RONI                  920 non-null    float64
 22  Fase ENSO (ONI)       920 non-null    object
 23  Intensidad (ONI)      479 non-null    object
 24  Fase ENSO (RONI)      920 non-null    object
 25  Intensidad (RONI)     480 non-null    object
dtypes: float64(17), int64(1), object(8)
memory usage: 187.2+ KB

In [64]:
prueba.describe() #Aca veo datos mas estadisticos como el min, max, percentiles, promedio etc

,Year,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,Nino 4 SST Anomaly,TNI,SOI,SOI estandarizado,OLR,OLR anomalia,PNA,MEI.v2,ONI,RONI
count,921.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,917.000000,909.000000,909.000000,612.000000,612.000000,921.000000,573.000000,920.000000,920.000000
mean,1987.876221,23.055741,-0.239412,25.790414,-0.202723,26.906362,-0.173878,28.406939,-0.241874,-0.266052,0.241914,0.147855,0.061275,0.976471,0.051977,-0.065654,0.020978,0.023337
std,22.168080,2.268865,1.104712,1.293583,0.903206,0.988674,0.871854,0.726662,0.690128,1.222150,1.557048,0.941042,0.973791,15.191442,0.997513,0.986425,0.790342,0.807785
min,1950.000000,18.920000,-3.090000,22.580000,-2.400000,24.250000,-2.450000,26.300000,-2.210000,-2.674000,-6.000000,-3.600000,-2.800000,-44.000000,-3.070000,-2.420000,-2.040000,-1.950000
25%,1969.000000,21.150000,-0.980000,24.790000,-0.820000,26.212500,-0.780000,27.920000,-0.720000,-1.168000,-0.700000,-0.400000,-0.600000,-9.125000,-0.660000,-0.770000,-0.510000,-0.500000
50%,1988.000000,22.810000,-0.410000,25.790000,-0.300000,26.975000,-0.250000,28.460000,-0.190000,-0.409000,0.300000,0.200000,0.200000,2.400000,0.120000,-0.150000,-0.040000,-0.030000
75%,2007.000000,24.950000,0.320000,26.785000,0.300000,27.597500,0.357500,28.960000,0.250000,0.440000,1.300000,0.800000,0.700000,11.400000,0.740000,0.480000,0.500000,0.530000
max,2026.000000,29.230000,4.470000,29.220000,3.300000,29.420000,2.720000,30.210000,1.540000,4.638000,4.800000,2.900000,2.300000,36.000000,2.660000,2.850000,2.590000,2.400000

In [65]:
prueba.isnull().sum() # Aca me muestra de cada columna suma los valores null

Date                      0
Year                      0
Month                     0
Nino 1+2 SST              3
Nino 1+2 SST Anomaly      3
Nino 3 SST                3
Nino 3 SST Anomaly        3
Nino 3.4 SST              3
Nino 3.4 SST Anomaly      3
Nino 4 SST                3
Nino 4 SST Anomaly        3
TNI                       4
SOI                      12
SOI estandarizado        12
OLR                     309
OLR anomalia            309
PNA                       0
Season (2-Month)          0
MEI.v2                  348
Season (3-Month)          0
ONI                       1
RONI                      1
Fase ENSO (ONI)           1
Intensidad (ONI)        442
Fase ENSO (RONI)          1
Intensidad (RONI)       441
dtype: int64