In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
prueba = pd.read_csv("indices_enso_noaa_pacifico.csv")
prueba.head() # Muestro las 5 primeras filas

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
0,1950-01-01,1950,JAN,23.01,-1.55,23.56,-2.10,24.55,-1.99,26.94,...,-2.34,DJ,NaN,DJF,-1.32,-1.19,La Niña,Moderado,La Niña,Moderado
1,1950-02-01,1950,FEB,24.32,-1.78,24.89,-1.52,25.06,-1.69,26.67,...,-1.04,JF,NaN,JFM,-1.20,-1.08,La Niña,Moderado,La Niña,Moderado
2,1950-03-01,1950,MAR,25.11,-1.38,26.36,-0.84,25.87,-1.42,26.52,...,0.24,FM,NaN,FMA,-1.12,-0.96,La Niña,Moderado,La Niña,Moderado
3,1950-04-01,1950,APR,23.63,-1.90,26.44,-1.14,26.28,-1.54,26.90,...,0.01,MA,NaN,MAM,-1.08,-1.00,La Niña,Moderado,La Niña,Moderado
4,1950-05-01,1950,MAY,22.68,-1.74,25.69,-1.57,26.18,-1.75,27.73,...,-0.55,AM,NaN,AMJ,-1.10,-0.99,La Niña,Moderado,La Niña,Moderado

In [23]:
prueba.tail() # Muestro las 5 ultimas filas

,Date,Year,Month,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,...,PNA,Season (2-Month),MEI.v2,Season (3-Month),ONI,RONI,Fase ENSO (ONI),Intensidad (ONI),Fase ENSO (RONI),Intensidad (RONI)
916,2026-05-01,2026,MAY,26.23,1.82,28.41,1.16,28.83,0.90,30.00,...,-1.2693,AM,0.27,AMJ,0.95,0.49,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
917,2026-06-01,2026,JUN,25.94,2.82,28.33,1.71,29.17,1.44,30.19,...,-0.5005,MJ,1.52,MJJ,1.39,0.97,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
918,2026-07-01,2026,JUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6149,JJ,2.41,JJA,1.80,1.36,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
919,2026-08-01,2026,AUG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0797,JA,2.54,JAS,2.16,1.69,El Niño,Muy fuerte,El Niño (provisorio),Fuerte
920,2026-09-01,2026,SEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.6415,AS,2.37,ASO,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
print("Dimensiones", prueba.shape)
print("Filas:", prueba.shape[0], " Columnas:", prueba.shape[1])

Dimensiones (921, 26)
Filas: 921  Columnas: 26

In [25]:
prueba.info() # Me sirve para saber que tipo de objeto tiene cada columna, tambien veo los null como por ejemplo de la columna 18 "MEI.v2" tiene 573 no null(datos) y el resto estan vacios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  921 non-null    object
 1   Year                  921 non-null    int64
 2   Month                 921 non-null    object
 3   Nino 1+2 SST          918 non-null    float64
 4   Nino 1+2 SST Anomaly  918 non-null    float64
 5   Nino 3 SST            918 non-null    float64
 6   Nino 3 SST Anomaly    918 non-null    float64
 7   Nino 3.4 SST          918 non-null    float64
 8   Nino 3.4 SST Anomaly  918 non-null    float64
 9   Nino 4 SST            918 non-null    float64
 10  Nino 4 SST Anomaly    918 non-null    float64
 11  TNI                   917 non-null    float64
 12  SOI                   909 non-null    float64
 13  SOI estandarizado     909 non-null    float64
 14  OLR                   612 non-null    float64
 15  OLR anomalia          612 non-null    float64
 16  PNA                   921 non-null    float64
 17  Season (2-Month)      921 non-null    object
 18  MEI.v2                573 non-null    float64
 19  Season (3-Month)      921 non-null    object
 20  ONI                   920 non-null    float64
 21  RONI                  920 non-null    float64
 22  Fase ENSO (ONI)       920 non-null    object
 23  Intensidad (ONI)      479 non-null    object
 24  Fase ENSO (RONI)      920 non-null    object
 25  Intensidad (RONI)     480 non-null    object
dtypes: float64(17), int64(1), object(8)
memory usage: 187.2+ KB

In [26]:
prueba.describe() #Aca veo datos mas estadisticos como el min, max, percentiles, promedio etc

,Year,Nino 1+2 SST,Nino 1+2 SST Anomaly,Nino 3 SST,Nino 3 SST Anomaly,Nino 3.4 SST,Nino 3.4 SST Anomaly,Nino 4 SST,Nino 4 SST Anomaly,TNI,SOI,SOI estandarizado,OLR,OLR anomalia,PNA,MEI.v2,ONI,RONI
count,921.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,917.000000,909.000000,909.000000,612.000000,612.000000,921.000000,573.000000,920.000000,920.000000
mean,1987.876221,23.055741,-0.239412,25.790414,-0.202723,26.906362,-0.173878,28.406939,-0.241874,-0.266052,0.241914,0.147855,0.061275,0.976471,0.051977,-0.065654,0.020978,0.023337
std,22.168080,2.268865,1.104712,1.293583,0.903206,0.988674,0.871854,0.726662,0.690128,1.222150,1.557048,0.941042,0.973791,15.191442,0.997513,0.986425,0.790342,0.807785
min,1950.000000,18.920000,-3.090000,22.580000,-2.400000,24.250000,-2.450000,26.300000,-2.210000,-2.674000,-6.000000,-3.600000,-2.800000,-44.000000,-3.070000,-2.420000,-2.040000,-1.950000
25%,1969.000000,21.150000,-0.980000,24.790000,-0.820000,26.212500,-0.780000,27.920000,-0.720000,-1.168000,-0.700000,-0.400000,-0.600000,-9.125000,-0.660000,-0.770000,-0.510000,-0.500000
50%,1988.000000,22.810000,-0.410000,25.790000,-0.300000,26.975000,-0.250000,28.460000,-0.190000,-0.409000,0.300000,0.200000,0.200000,2.400000,0.120000,-0.150000,-0.040000,-0.030000
75%,2007.000000,24.950000,0.320000,26.785000,0.300000,27.597500,0.357500,28.960000,0.250000,0.440000,1.300000,0.800000,0.700000,11.400000,0.740000,0.480000,0.500000,0.530000
max,2026.000000,29.230000,4.470000,29.220000,3.300000,29.420000,2.720000,30.210000,1.540000,4.638000,4.800000,2.900000,2.300000,36.000000,2.660000,2.850000,2.590000,2.400000

In [27]:
prueba.isnull().sum() # Aca me muestra de cada columna suma los valores null

Date                      0
Year                      0
Month                     0
Nino 1+2 SST              3
Nino 1+2 SST Anomaly      3
Nino 3 SST                3
Nino 3 SST Anomaly        3
Nino 3.4 SST              3
Nino 3.4 SST Anomaly      3
Nino 4 SST                3
Nino 4 SST Anomaly        3
TNI                       4
SOI                      12
SOI estandarizado        12
OLR                     309
OLR anomalia            309
PNA                       0
Season (2-Month)          0
MEI.v2                  348
Season (3-Month)          0
ONI                       1
RONI                      1
Fase ENSO (ONI)           1
Intensidad (ONI)        442
Fase ENSO (RONI)          1
Intensidad (RONI)       441
dtype: int64